name: aigraphy_flutter
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  meta: ^1.9.1
  responsive_framework: ^0.2.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  path_provider: ^2.1.2
  dotted_border: ^2.1.0
  flutter_easyloading: ^3.0.5
  share_plus: ^7.2.2
  intl: ^0.18.1
  webview_flutter: ^4.5.0
  photo_view: ^0.14.0
  stream_transform: ^2.1.0
  lottie: ^2.7.0
  photo_manager_image_provider: ^1.0.0
  photo_manager: ^3.0.0
  graphql: ^5.1.3
  dio: ^5.4.1
  image_picker: ^1.0.7
  url_launcher: ^6.2.4
  purchases_flutter: ^6.24.0
  http: ^1.1.0
  flutter_local_notifications: ^17.0.0
  bloc_concurrency: ^0.2.4
  easy_localization: ^3.0.5
  image_gallery_saver: ^2.0.3
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^4.2.1
  bot_toast: ^4.1.3
  image_editor_plus: ^1.0.4
  confetti: ^0.7.0
  cached_network_image: ^3.3.1
  sqflite_common_ffi: ^2.3.0+4
  sqflite: ^2.3.2
  flutter_native_splash: ^2.3.7
  video_player: ^2.8.3

  firebase_messaging: ^14.7.9
  google_sign_in: ^6.1.6
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  flutter_facebook_auth: ^6.0.3
  firebase_analytics: ^10.5.1
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: ClashGrotesk
      fonts:
        - asset: assets/fonts/ClashGrotesk-Bold.otf
        - asset: assets/fonts/ClashGrotesk-Medium.otf
        - asset: assets/fonts/ClashGrotesk-Regular.otf
        - asset: assets/fonts/ClashGrotesk-SemiBold.otf
        - asset: assets/fonts/ClashGrotesk-Light.otf
include: package:pedantic/analysis_options.yaml

flutter_native_splash:
  image: assets/images/splash.png
  color: "010202"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon_app.png"
  min_sdk_android: 21
  remove_alpha_ios: true
